### ISSUE TITLE
About listen contact

### ISSUE THREAD

**Issue by adsizmusa** [Ben-Baert/flutter_listentocontacts#1]
Your plugin working very good on background.

but I think the plugin when listen contact changed. It can not find changed contact and contact detail. It is  find the value true or false

**Comment by Ben-Baert** [comment]
Yes, it doesn't say which contact has changed. This is a limitation of the system APIs, not the plugin. You need to maintain a database and compare if you want to detect changes.

**Comment by adsizmusa** [comment]
Thank you very much for your answer. I have a app for assistan of the phone.

I keep the contact list in my database 

For example if phone has 10 thousands contact this plugin get the contacts it takes  very long time (10 minutes or 20 minutes). after I am compore get the contact list item to list of my contact list in my database . It takes very long time
